import sys
sys.path.append("../")
from appJar import gui
def f1(e): print(e)
app=gui()
app.setFont(12)
app.addLabel("l1", "Text here")
app.createRightClickMenu("showme", False)
app.addMenuItem("showme", "This one ...", f1)
app.setLabelRightClick("l1", "showme")
app.addMenuEdit(True)
app.addMenuSeparator("EDIT")
app.addMenuItem("EDIT", "This one ...", f1, shortcut="control+q")
app.addMenuItem("Other", "Other 1", f1, shortcut="alt+p", underline=1)
app.addMenuItem("Other", "Other 2", f1, shortcut="ctrl-l", underline=1)
app.addMenuItem("Other", "Other 3", f1, shortcut="shift-w", underline=1)
app.addMenuItem("Other", "Other 4", f1, shortcut="ctrl-shift+t", underline=1)
app.addMenuItem("Other", "Other 5", f1, shortcut="alt-shift+t", underline=1)
app.addMenuItem("Other", "Other 6", f1, shortcut="ctrl-alt+t", underline=1)
app.addEntry("e1")
app.addNumericEntry("ne1")
app.addSecretEntry("se1")
app.addOptionBox("o1", ["a", "b", "c", "d"])
app.addTickOptionBox("to1", ["a", "b", "c", "d"])

app.addScrolledTextArea("text")
app.go()
