from appJar import gui

app=gui()

app.addLabel("1", "Welcome to NoteBook 1.0")
app.setBg("blue")
app.startLabelFrame("Notebooks")
app.setBg("yellow")

app.startNoteBook("Book1", 0, 0)
app.startNoteTab("aaa")
app.setBg("red")
app.addLabel("11", "Stuff here")
app.addLabel("12", "Stuff here")
app.addLabel("13", "Stuff here")
app.stopNoteTab()
app.startNoteTab("bbb")
app.addLabel("21", "Stuff here")
app.addLabel("22", "Stuff here")
app.addLabel("23", "Stuff here")
app.stopNoteTab()
app.startNoteTab("ccc")
app.addLabel("31", "Stuff here")
app.addLabel("32", "Stuff here")
app.addLabel("33", "Stuff here")
app.stopNoteTab()
app.stopNoteBook()

app.startNoteBook("Book2", 0, 1)
app.startNoteTab("aaa")
app.addLabel("211", "Stuff here")
app.addLabel("212", "Stuff here")
app.addLabel("213", "Stuff here")
app.stopNoteTab()
app.startNoteTab("bbb")
app.addLabel("221", "Stuff here")
app.addLabel("222", "Stuff here")
app.addLabel("223", "Stuff here")
app.stopNoteTab()
app.startNoteTab("ccc")
app.addLabel("231", "Stuff here")
app.addLabel("232", "Stuff here")
app.addLabel("233", "Stuff here")
app.stopNoteTab()
app.stopNoteBook()

app.stopLabelFrame()

app.go()
